### ISSUE TITLE
Epic fail...

### ISSUE THREAD

**Issue by johndockinson** [Satoqz/Discord-Bot-CLI#1]
You never included any of the repositories or whatever actually required to run this.
`Discord-Bot-CLI-master>npm install
npm WARN bot@1.0.0 No repository field.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@derhuerst/http-basic/-/http-basic-8.2.0.tgz
npm ERR! 404
npm ERR! 404  '@derhuerst/http-basic@8.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'Discord-Bot-CLI-master'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

**Comment by Satoqz** [comment]
I will take a look into it, but ive seen that other people have had no problems installing

**Comment by Satoqz** [comment]
I have no idea what you're doing wrong - here's what I did:

1. clone the repsitory

2. run `npm i` in the project root (where the package.json file is)

3. successful install

Are you sure that you're running the command in the correct folder? The above error always occurs when you're running `npm install` in a folder without a package.json. It seems like you downloaded the repository as a zip and didn't go far enough into the project structure after unpacking.

Hope I could help out.

**Comment by johndockinson** [comment]
> It seems like you downloaded the repository as a zip and didn't go far enough into the project structure after unpacking.
> 
> Hope I could help out.

Yes, that I did. I'm actually unsure how to clone repositories and run things like that, I've just been downloading and extracting most .zipped repos and running them like that from their directory fine, this one is the only one I've had issues with so far. I don't have much experience in git, so I appreciate the help.. ^^
